apiVersion: apps/v1
kind: Deployment
metadata:
  name: metersystem-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metersystem-api
  template:
    metadata:
      labels:
        app: metersystem-api
    spec:
      containers:
        - name: metersystem-api
          image: metersystem-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: metersystem-api
spec:
  selector:
    app: metersystem-api
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
